name: Build yuanwei-icon module

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows version
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          repository: YuanWeiSite/yuanwei-icon-python
          token: ${{ secrets.TK_ICON }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with Nuitka
        run: |
          nuitka --onefile --output-filename=yuanwei-icon.exe --remove-output .\main.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: yuanwei-icon.exe
